// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MutrajimAPI.Models;

namespace MutrajimAPI.Migrations
{
    [DbContext(typeof(MutrajimDbContext))]
    [Migration("20211220211607_SecondMigration")]
    partial class SecondMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("MutrajimAPI.Models.Project", b =>
                {
                    b.Property<int>("ProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("SourceLanguage")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SourceLanguageName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TargetLanguage")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TargetLanguageName")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProjectID");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("MutrajimAPI.Models.TranslationModel", b =>
                {
                    b.Property<int>("KeyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("KeyID");

                    b.ToTable("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
